---
title: "Into Veteran Suicide in the U.S. "
author: "Daniel Fang, Bella Ding"
output: 
  prettydoc::html_pretty:
    theme: tactile
    toc: true


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(ggplot2)
library(readr)
library(dplyr)
library(ggthemes)
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(gganimate)     # for adding animation layers to ggplots
library(transformr)    # for "tweening" (gganimate)
library(gifski)        # need the library for creating gifs but don't need to load each time
library(shiny)         # for creating interactive apps
```
 
 
## Read Data 
 
```{r}
# read data
vet_deaths_sex_age_2005_2018 <- read_csv("data/vet_deaths_sex_age_2005_2018.csv")
nonvet_deaths_sex_age_2005_2018 <- read_csv("data/nonvet_deaths_sex_age_2005_2018.csv")


pop_deaths_state_age_2005_2018 <- read_csv("data/pop_deaths_state_age_2005_2018.csv")
pop_deaths_state_method_2005_2018 <- read_csv("data/pop_deaths_state_method_2005_2018.csv")
```


## Data Cleaning


```{r}
# data cleaning: veteran suicides by age, sex  (as compare to non-veteran)
# usage: for general veteran suicides plots
nonvet_total <- nonvet_deaths_sex_age_2005_2018 %>% 
  select(-nonvet_rate, -nonvet_deaths, -nonvet_pop, -male_nonvet_rate, -female_nonvet_rate) %>% 
  mutate(age = ifelse(age_2 == "." | age_2=="55", "55+", age_2)) %>% 
  mutate(female_nonvet_deaths = as.numeric(gsub(",","",ifelse(female_nonvet_deaths==".", "0",female_nonvet_deaths)))) %>% 
  mutate(female_nonvet_pop = as.numeric(gsub(",","",ifelse(female_nonvet_pop==".", "0",female_nonvet_pop)))) %>% 
  select(-c(age_1, age_2)) %>% 
  group_by(Year, age) %>% 
  summarise_all(.funs = sum) %>% 
  #mutate(nonvet_rate = nonvet_deaths*100000/nonvet_pop) %>% 
  mutate(male_nonvet_rate = male_nonvet_deaths*100000/male_nonvet_pop) %>% 
  mutate(female_nonvet_rate = female_nonvet_deaths*100000/female_nonvet_pop) %>% 
  filter(age!="Total")

vet_total <- vet_deaths_sex_age_2005_2018 %>% 
  select(-vet_rate,-vet_deaths, -vet_pop, -male_vet_rate, -female_vet_rate) %>% 
  mutate(age = ifelse(age_2 == "." | age_2=="55", "55+", age_2)) %>% 
  mutate(female_vet_deaths = as.numeric(gsub(",","",ifelse(female_vet_deaths==".", "0",female_vet_deaths)))) %>% 
  mutate(female_vet_pop = as.numeric(gsub(",","",ifelse(female_vet_pop==".", "0",female_vet_pop)))) %>% 
  select(-c(age_1, age_2)) %>% 
  group_by(Year, age) %>% 
  summarise_all(.funs = sum) %>% 
  #mutate(vet_rate = vet_deaths*100000/vet_pop) %>% 
  mutate(male_vet_rate = male_vet_deaths*100000/male_vet_pop) %>% 
  mutate(female_vet_rate = female_vet_deaths*100000/female_vet_pop) %>% 
  filter(age!="Total")


pop_deaths_sex_age_2005_2018 <- nonvet_total %>% 
  left_join(vet_total) %>% 
  pivot_longer(
    cols = -c(Year,age),
    names_to = c("sex", "group", "benchmark"),
    names_pattern = "(.*)_(.*)_(.*)",
    values_to = "value"
  ) %>% 
  pivot_wider(
    id_cols = c(Year, age, sex, group),
    names_from = benchmark,
    values_from = value
  )

pop_deaths_sex_age_2005_2018
```


```{r}
# data cleaning: veteran suicide by state (region)!!
# usage: for drawing maps
pop_deaths_state_age <- pop_deaths_state_age_2005_2018 %>% 
  filter(age=="Total" & state!="All" & state!= "Total U.S.") %>% 
  select(-age) %>% 
  mutate(vet_deaths=as.numeric(vet_deaths)) %>% 
  mutate(vet_rate=as.numeric(vet_rate)) %>% 
  mutate(pop_deaths=as.numeric(pop_deaths)) %>% 
  mutate(pop_rate=as.numeric(pop_rate))

pop_deaths_state_age
```

```{r}
# data cleaning: veteran suicides by methods (as compare to general population)
# usage: for general veteran suicides plots
pop_deaths_state_method <- pop_deaths_state_method_2005_2018 %>% 
  filter(state!="All" & state!= "Total U.S.") %>% 
  mutate(group=ifelse(group=="Veteran Method", "Veteran", "Population")) %>% 
  mutate(deaths=as.numeric(deaths)) 

pop_deaths_state_method
```


## Plots

```{r}
# figure 1
pop_deaths_state_method %>% 
  ggplot(aes(x=group,y=deaths, fill=method))+
    geom_col(position = "fill")+
    labs(title = "Suicide Methods Comparison: Veteran vs. General Population", y = "")+
  theme_minimal()
```

```{r}
# figure 2
pop_deaths_sex_age_2005_2018 %>%
  ggplot(aes(y = sex, x = deaths))+
  theme_igray()+
    geom_col() +
  labs(title = "Number of Veteran Suicides by Gender", y = "Sex", x = "# of suicides")+
  theme_classic()
```


```{r}
vet_deaths_sex_age_2005_2018 %>%
  ggplot(aes(y = vet_deaths, x = age_1))+
  theme_igray()+
    geom_col() +
  labs(title = "Number of Veteran Suicides by Age", y = "Total Cases", x = "Age Intervals")+
  theme_classic()
```

```{r}
states_map <- map_data("state")
pop_deaths_state_age %>%
  filter(Year == "2018") %>%
  mutate(state = str_to_lower(state)) %>%
  ggplot(aes()) +
  geom_map(aes(map_id = state, 
               fill = vet_rate), 
           map = states_map)+
  expand_limits(x = states_map$long, y = states_map$lat)+
  scale_fill_gradient2()+
  theme_map()+
  theme(legend.background =  element_blank())+
  labs(title = "Percentage of Veteran Suicides in Total Veteran Population in the U.S.", fill = "%")

```

```{r}
vet_deaths_sex_age_2005_2018 %>%
  filter(age_1 == "Total") %>%
  ggplot(aes(x = Year, y = vet_deaths)) +
  geom_line(color = "blue")+
  geom_point()+
  labs(title = "Number of Veteren Suicides from 2005 to 2018", y = "Cases")+
  theme_minimal()
```

 
 
 
 
 
